### ISSUE TITLE
Use DBUS for controlling USB settings

### ISSUE THREAD

**Issue by philippedeswert** [jklingen/harbour-usb-switch#1]
Hi,

Just noticed your app. Did you know you can actually control USB settings over DBUS?

Here the documentation : https://github.com/nemomobile/usb-moded/blob/master/docs/usb_moded-doc.txt

You can also check lipstick and nemo-qml-plugin-systemsettings for some examples on how to do things as the code is there.
Or ping me on IRC in #jollamobile, on freenode. Nick is phdeswer

**Comment by jklingen** [comment]
Hi Phillipe,

Good news: I finally had a look at this - next version of USB switch will use DBUS to interact with usb_moded.

Thanks again for the heads-up.
Best regards,
Jens :)

**Comment by philippedeswert** [comment]
You're welcome! And feel free to ping me if you run into an issue.

**Comment by jklingen** [comment]
Thanks a lot - no issues so far, but good to know :smile:

**Comment by jklingen** [comment]
Released in [version 0.2](https://github.com/jklingen/harbour-usb-switch/releases/tag/v0.2)
